"""
compare_excel.py
────────────────
Deep 1:1 comparison between:
  ORIG = "NIKE Valuation strategy.xlsx"   (the ground-truth Nike workbook)
  GEN  = generated from the Flask API     (our output)

Steps:
  1. Hit /api/export/NKE to get generated bytes
  2. Load both workbooks with openpyxl
  3. Print the sheet names in ORIG and GEN
  4. Iterate every row/col in the Nike "valuation" sheet (or whichever sheet maps)
  5. Compare labels (col A) and numeric values
  6. Report every mismatch
"""

import io
import sys
import urllib.request
import openpyxl
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter

ORIG_PATH = r"NIKE Valuation strategy.xlsx"
API_URL   = "http://127.0.0.1:5000/api/export/NKE"

# ── helpers ──────────────────────────────────────────────────────────────────

def numeric(v):
    if v is None:
        return None
    if isinstance(v, (int, float)):
        return float(v)
    try:
        return float(str(v).replace(",", "").replace("$", "").replace("%", ""))
    except Exception:
        return None

def cell_str(v):
    if v is None:
        return ""
    return str(v).strip()

def pct_diff(a, b):
    if a is None or b is None:
        return None
    if abs(b) < 0.01:
        return None if abs(a) < 0.01 else float("inf")
    return abs(a - b) / abs(b) * 100

# ── load workbooks ────────────────────────────────────────────────────────────

print("Loading original:", ORIG_PATH)
orig_wb = load_workbook(ORIG_PATH, data_only=True)
print("  ORIG sheets:", orig_wb.sheetnames)

print("Fetching generated Excel from API...")
try:
    with urllib.request.urlopen(API_URL, timeout=30) as r:
        gen_bytes = r.read()
    print(f"  API response: {len(gen_bytes)} bytes")
except Exception as e:
    print(f"ERROR: could not reach API: {e}")
    sys.exit(1)

gen_wb = load_workbook(io.BytesIO(gen_bytes), data_only=True)
print("  GEN sheets:", gen_wb.sheetnames)

# ── pick sheets ───────────────────────────────────────────────────────────────

# The original Nike workbook has a sheet called "valuation" (or similar)
# We need to find which sheet in orig has the rows we care about.
def find_sheet(wb, candidates):
    for name in candidates:
        if name in wb.sheetnames:
            return wb[name]
    # fallback: first sheet
    return wb.active

orig_ws = find_sheet(orig_wb, ["valuation", "Valuation", "Model", "DCF"])
gen_ws  = find_sheet(gen_wb,  ["valuation", "Valuation"])

print(f"\nComparing ORIG sheet '{orig_ws.title}'  vs  GEN sheet '{gen_ws.title}'")
print(f"  ORIG dimensions: {orig_ws.dimensions}  max_row={orig_ws.max_row}  max_col={orig_ws.max_column}")
print(f"  GEN  dimensions: {gen_ws.dimensions}   max_row={gen_ws.max_row}   max_col={gen_ws.max_column}")

# ── full dump of ORIG sheet ───────────────────────────────────────────────────
print("\n" + "="*80)
print("ORIG SHEET — ALL NON-EMPTY CELLS (first 600 rows, cols A–R)")
print("="*80)
N_COLS = 18   # A=1 through R=18

orig_data = {}   # (row, col) -> value
for row_idx in range(1, min(orig_ws.max_row + 1, 601)):
    row_vals = []
    for col_idx in range(1, N_COLS + 1):
        v = orig_ws.cell(row_idx, col_idx).value
        orig_data[(row_idx, col_idx)] = v
        if v is not None:
            row_vals.append((col_idx, v))
    if row_vals:
        parts = [f"R{row_idx}:"]
        for ci, v in row_vals:
            parts.append(f"  {get_column_letter(ci)}={repr(v)}")
        print("".join(parts))

# ── full dump of GEN sheet ────────────────────────────────────────────────────
print("\n" + "="*80)
print("GEN SHEET — ALL NON-EMPTY CELLS (first 600 rows, cols A–R)")
print("="*80)

gen_data = {}
for row_idx in range(1, min(gen_ws.max_row + 1, 601)):
    row_vals = []
    for col_idx in range(1, N_COLS + 1):
        v = gen_ws.cell(row_idx, col_idx).value
        gen_data[(row_idx, col_idx)] = v
        if v is not None:
            row_vals.append((col_idx, v))
    if row_vals:
        parts = [f"R{row_idx}:"]
        for ci, v in row_vals:
            parts.append(f"  {get_column_letter(ci)}={repr(v)}")
        print("".join(parts))

# ── LABEL comparison (col A) ─────────────────────────────────────────────────
print("\n" + "="*80)
print("LABEL COMPARISON  (col A, rows 1-600)")
print("="*80)
for row_idx in range(1, 601):
    o_lbl = cell_str(orig_data.get((row_idx, 1)))
    g_lbl = cell_str(gen_data.get((row_idx, 1)))
    if o_lbl or g_lbl:
        match = "OK" if o_lbl.lower() == g_lbl.lower() else "MISMATCH"
        flag  = "" if match == "OK" else "  <<<< LABEL DIFF"
        print(f"R{row_idx:4d}  [{match}]  ORIG={repr(o_lbl):<50s}  GEN={repr(g_lbl)}{flag}")

# ── NUMERIC comparison (cols B-R) ────────────────────────────────────────────
print("\n" + "="*80)
print("NUMERIC COMPARISON  (cols B-R, rows 1-600, threshold >1%)")
print("="*80)
mismatches = []
for row_idx in range(1, 601):
    for col_idx in range(2, N_COLS + 1):
        o_v = orig_data.get((row_idx, col_idx))
        g_v = gen_data.get((row_idx, col_idx))
        o_n = numeric(o_v)
        g_n = numeric(g_v)
        if o_n is None and g_n is None:
            continue
        diff = pct_diff(o_n, g_n)
        if diff is None:
            # one is None, other is numeric
            if o_n is not None or g_n is not None:
                mismatches.append((row_idx, col_idx, o_v, g_v, "MISSING"))
        elif diff > 1.0:
            mismatches.append((row_idx, col_idx, o_v, g_v, f"{diff:.1f}%"))

for row_idx, col_idx, o_v, g_v, reason in mismatches:
    lbl = cell_str(orig_data.get((row_idx, 1)) or gen_data.get((row_idx, 1)))
    col_ltr = get_column_letter(col_idx)
    print(f"R{row_idx:4d} {col_ltr}  [{reason:>10s}]  ORIG={repr(o_v):<25}  GEN={repr(g_v):<25}  label={repr(lbl)}")

print(f"\nTotal numeric mismatches (>1%): {len(mismatches)}")
print("\nDONE.")
